#!/bin/bash

docker_networks=$(dockerNetworks6)
if [ -z "$docker_networks" ]
then
  echo "No inet6 network"
  exit
fi
IFS=',' read -ra networks <<< "$docker_networks"

# echo "Enabling connection to secure interface6 and docker network6"

ip6tables -F
ip6tables -X

ip6tables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
ip6tables -A INPUT -i lo -j ACCEPT
for net in "${networks[@]}"
do
  network=($net)
  ip6tables -A INPUT -i "${network[0]}" -s "${network[1]}" -j ACCEPT
done

ip6tables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
ip6tables -A OUTPUT -o lo -j ACCEPT
ip6tables -A OUTPUT -o tap+ -j ACCEPT
ip6tables -A OUTPUT -o tun+ -j ACCEPT
ip6tables -A OUTPUT -o nordlynx+ -j ACCEPT
for net in "${networks[@]}"
do
  network=($net)
  ip6tables -A OUTPUT -o "${network[0]}" -d "${network[1]}" -j ACCEPT
done
ip6tables -A OUTPUT -o eth0 -p udp -m udp --dport 53 -j ACCEPT
ip6tables -A OUTPUT -o eth0 -p udp -m udp --dport 51820 -j ACCEPT
ip6tables -A OUTPUT -o eth0 -p tcp -m tcp --dport 1194 -j ACCEPT
ip6tables -A OUTPUT -o eth0 -p udp -m udp --dport 1194 -j ACCEPT
ip6tables -A OUTPUT -o eth0 -p tcp -m tcp --dport 443 -j ACCEPT

ip6tables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
ip6tables -A FORWARD -i lo -j ACCEPT
for net in "${networks[@]}"
do
  network=($net)
  ip6tables -A FORWARD -i "${network[0]}" -d "${network[1]}" -j ACCEPT
  ip6tables -A FORWARD -i "${network[0]}" -s "${network[1]}" -j ACCEPT
done

ip6tables -t nat -A POSTROUTING -o tap+ -j MASQUERADE
ip6tables -t nat -A POSTROUTING -o tun+ -j MASQUERADE
ip6tables -t nat -A POSTROUTING -o nordlynx+ -j MASQUERADE
