#!/bin/bash

[[ -n ${WHITELIST} && -z ${ALLOW_LIST} ]] && ALLOW_LIST=${WHITELIST}
if [[ -n ${ALLOW_LIST} ]]
then
  for domain in ${ALLOW_LIST//[;,]/ }
  do
    domain=$(echo "$domain" | sed 's/^.*:\/\///;s/\/.*$//')
    echo -e $(date "+%F %T%z") "\tINFO\tEnabling connection to host ${domain}"
    iptables  -A OUTPUT -o eth0 -d "${domain}" -j ACCEPT 2>/dev/null
    ip6tables -A OUTPUT -o eth0 -d "${domain}" -j ACCEPT 2>/dev/null
  done
fi
