#!/bin/bash

if ! iptables -L > /dev/null 2>&1
then
  echo -e $(date "+%F %T %z") "\tWARNING\tFATAL: iptables is not functional. Ensure your container config adds --cap-add=NET_ADMIN,NET_RAW" 1>&2
  # Null route rather than leaving traffic unprotected.
  ip route del default
  ip route del 0.0.0.0/1 > /dev/null 2>&1
  ip route add default via 127.0.0.1
  echo -e $(date "+%F %T %z") "\tWARNING\t--- Due to errors, routing has been disabled ---" 1>&2
  # Don't allow execution to proceed as traffic may not be protected. Don't exit either as
  # containers that expect to be behind the VPN will route through the normal network.
  while true
  do
    sleep 3600
  done
fi

[[ -z "${PASS}" ]] && [[ -f "${PASSFILE}" ]] && PASS="$(head -n 1 "${PASSFILE}")"
nordvpn logout > /dev/null

if [[ -n ${TOKEN} ]]
then
  nordvpn login --token "${TOKEN}" || {
    echo -e $(date "+%F %T %z") "\tWARNING\tInvalid token."
    exit 1
  }
else
  nordvpn login --legacy --username "${USER}" --password "${PASS}" || {
    echo -e $(date "+%F %T %z") "\tWARNING\tInvalid Username or password."
    exit 1
  }
fi

exit 0
