#!/bin/bash
shopt -s nocasematch

[[ -n ${PRE_CONNECT} ]] && eval ${PRE_CONNECT}

## Get RECOMMENDED if internet accessible
if [[ $(curl -s --connect-timeout 5 "${CHECK_CONNECTION_URL:-https://www.google.com}") ]]
then
  ## Obtain recommended server from API
  SERVER=$1
  if [[ -z ${SERVER} ]]
  then
    RECOMMENDED=$(nord_recommend)
    SERVER=$(echo $RECOMMENDED | jq --raw-output .servername)
  fi

  ## Determine is valid servername
  if [[ -z ${SERVER} || ${SERVER} == "null" ]]
  then
    if [[ -n ${CONNECTION_FILTERS} ]]
    then
      echo -e $(date "+%F %T%z") "\tWARNING\tInvalid connection string; retrying without filters"
    else
      echo -e $(date "+%F %T%z") "\tWARNING\tCannot connect to recommended; retrying with default"
    fi
    ## Let NordVPN client select the server
    unset SERVER
  fi
else
    ## Firewall, notify that filters not to be used
    if [[ -n ${CONNECTION_FILTERS} ]]
    then
      echo -e $(date "+%F %T%z") "\tWARNING\tCannot evaluate filters; retrying with defaults"
    fi
fi

## Make the connection
current_sleep=1
until nordvpn connect ${SERVER} | grep -Ei -f /opt/reg-grep
do
  if [ ${current_sleep} -gt 32 ]
  then
    echo -e $(date "+%F %T%z") "\tCRITICAL\tUnable to connect; exiting"
    exit 1
  fi
  echo -e $(date "+%F %T%z") "\tWARNING\tUnable to connect; retrying in ${current_sleep} seconds."
  sleep ${current_sleep}
  current_sleep=$((current_sleep * 2))
done

[[ -n ${POST_CONNECT} ]] && eval ${POST_CONNECT}

exit 0
