#!/bin/bash

[[ -n ${PRE_CONNECT} ]] && eval ${PRE_CONNECT}

current_sleep=1
RECOMMENDED=$(nord_recommend)
SERVER=$(echo $RECOMMENDED | jq --raw-output .servername)
[[ -n ${SERVER} ]] || echo -e $(date "+%F %T%z") "\tWARNING\tInvalid connection string; exiting"; exit 1
ACTION=$(echo $RECOMMENDED | jq --raw-output .action)
if [[ ${ACTION} != "stay" ]]
  then
  until nordvpn connect ${SERVER} | grep -Ei -f /opt/reg-grep
  do
    if [ ${current_sleep} -gt 32 ]
    then
      echo -e $(date "+%F %T%z") "\tWARNING\tUnable to connect; exiting"
      exit 2
    fi
    echo -e $(date "+%F %T%z") "\tWARNING\tUnable to connect; retrying in ${current_sleep} seconds."
    sleep ${current_sleep}
    current_sleep=$((current_sleep * 2))
  done

  [[ -n ${POST_CONNECT} ]] && eval ${POST_CONNECT}
else
  host=$(echo ${RECOMMENDED} | jq --raw-output .hostname)
  echo "You are already connected to the recommended server ($host)"
fi
exit 0
