#!/bin/bash
CODE=0
STAT=$(nordvpn status | grep -Eio --color=never "Status: Connected") || CODE=1
if [[ -z "$STAT" || $CODE -ne 0 ]]
then
    STAT="Status: Disconnected"
    CODE=2
fi

if [ $CODE -eq 0 ]
then
    URI=https://nordvpn.com/wp-admin/admin-ajax.php?action=get_user_info_data
    CHK=$(curl -fs $URI) || CODE=3
    if [[ ! "$CHK" == true ]]
    then
        STAT="Status: Unstable"
        CODE=${CODE:-4}
    fi
fi
echo -n $STAT
exit $CODE
